# Generated by Django 3.1.8 on 2021-07-01 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0053_auto_20210701_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstatement',
            name='delegate',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Delegate statement', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='controls.statement'),
        ),
        migrations.AddField(
            model_name='statement',
            name='delegate',
            field=models.ForeignKey(blank=True, help_text='Delegate statement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegators', to='controls.statement'),
        ),
    ]
